{{- if .Values.gateway.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: maops-gateway-pdb
  namespace: {{ .Values.release.namespace }}
  labels:
    {{- include "maops.componentLabels" (dict "root" $ "component" "gateway") | nindent 4 }}
spec:
  minAvailable: {{ .Values.gateway.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "maops.selectorLabels" (dict "root" $ "component" "gateway") | nindent 6 }}
{{- end }}
