apiVersion: v1
kind: Service
metadata:
  name: maops-gateway
  namespace: {{ .Values.release.namespace }}
  labels:
    {{- include "maops.componentLabels" (dict "root" $ "component" "gateway") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "maops.selectorLabels" (dict "root" $ "component" "gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.containerPort }}
      targetPort: http
      protocol: TCP
