apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: maops-app-pdb
  namespace: maops-platform
  labels:
    app.kubernetes.io/name: maops-kubernetes-platform
    app.kubernetes.io/instance: maops-kubernetes-platform-day3
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: maops-kubernetes-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: maops-kubernetes-platform
      app.kubernetes.io/instance: maops-kubernetes-platform-day3
      app.kubernetes.io/component: app
