apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway-configmap.yaml
  - app-configmap.yaml
  - gateway-deployment.yaml
  - app-deployment.yaml
  - gateway-service.yaml
  - app-service.yaml
  - gateway-pdb.yaml
  - app-pdb.yaml
